### ISSUE TITLE
melpa pkg depends on unavailable "undo-tree-0.6.3"

### ISSUE THREAD

**Issue by dradetsky** [countvajhula/symex.el#1]
attempt to install yields

```
Package ‘undo-tree-0.6.3’ is unavailable 
```

**Comment by dradetsky** [comment]
fwiw, this isn't coming from symex, but from evil-cleverparens

**Comment by countvajhula** [comment]
Interestingly, searching for undo-tree on MELPA doesn't pull it up: https://melpa.org/#/?q=undo-tree
But it looks like it should be available on ELPA: https://elpa.gnu.org/packages/undo-tree.html
Is ELPA in your list of package archives to pull from?

**Comment by dradetsky** [comment]
it isn't. fwiw, i used to have a bunch of issues using both of them, which is why i intentionally didn't enable elpa for my new cfg setup. I agree that this is probably a fix, but I'm going to try to package undo-tree for melpa instead.

**Comment by countvajhula** [comment]
Closing this issue, feel free to create another one if you run into anything else @dradetsky !
