### ISSUE TITLE
symex-custom-keys and the hydra-menu

### ISSUE THREAD

**Issue by pepperblue** [countvajhula/symex.el#11]
When I use `symex-custom-keys` to remap or disable keys it works but it's not reflected correctly in the menu, e.g. the following configuration:
```
(use-package! symex
  :init
  (setq symex-custom-keys
        '(("j" symex-go-up "up")
          ("k" symex-go-down "down")
          ("F" nil nil))))
```
gives following menu-entries:
![symex-custom-keys](https://user-images.githubusercontent.com/3543271/80467558-406bb680-893e-11ea-820e-37c89b913d1f.jpg)

What's working for me is to use `defhydra+`-macro:
```
(use-package! symex
  :config
  (defhydra+ hydra-symex (:idle 1.0
                          :columns 4
                          :color pink
                          :body-pre (progn (evil-symex-state)
                                           (symex-select-nearest))
                          :post (deactivate-mark))
    "Symex mode"
    ("j" symex-go-up "up")
    ("k" symex-go-down "down")
    ("F" nil nil)))
```
resulting menu-entries:
![defhydra+](https://user-images.githubusercontent.com/3543271/80467735-8de82380-893e-11ea-9c0f-9ccea9f8c37c.jpg)

**Comment by countvajhula** [comment]
Did not know about `defhydra+` - fixed and added your suggestion to the README 👍
