### ISSUE TITLE
Up and down

### ISSUE THREAD

**Issue by Vurp** [countvajhula/symex.el#14]
What is considered to be "up" and "down" considering sexps?

When I think of a complex lisp expression I think of it as a tree with
the most outermost form being the root of this tree. As such moving
"up" would mean moving closer to the root and "down" would mean moving
to a leaf. But in symex this seems to be reversed.

**Comment by countvajhula** [comment]
Take a look at the [Installation and Usage](https://github.com/countvajhula/symex.el#installation-and-usage) section of the README, where it explains how you can change the keybindings to whatever you find most intuitive (and the included example shows how to flip the up/down axis).

By default, as the root of a real tree 🎄 is at the bottom of the tree, going towards the root, i.e. the outermost form, is accomplished by going "down." But as outermost forms are found on the first line of a symex, this also means that going "down" the tree usually means going _up_ the page, which may be unexpected. Personally, it didn't take me long to get used to it (maybe having a mental image of it as a tree helps), but you should of course use whatever you find most intuitive.

**Comment by countvajhula** [comment]
@Vurp I'm closing this issue, but feel free to reopen or comment below if you still have questions.
