### ISSUE TITLE
what about a dsl for editing tree notation?

### ISSUE THREAD

**Issue by breck7** [countvajhula/symex.el#2]
saw this from racket post. interesting ideas. how about something similar for editing tree notation documents/tree language programs? like paren less s exp.

we have far fewer users, but are growing faster.

https://github.com/breck7/jtree

**Comment by countvajhula** [comment]
Symex uses third party packages to derive the underlying tree representation, and at the moment these packages (paredit and lispy) work specifically with Lisp code. In the future it could be made more generic by using something like https://github.com/tree-sitter/tree-sitter instead. That way, symex could work on non-Lisp languages as well, including tree notation, as long as they are supported by the AST package.

**Comment by breck7** [comment]
Cool, thanks for the information!
