### ISSUE TITLE
Support evil backend as an alternative to hydra

### ISSUE THREAD

**Issue by countvajhula** [countvajhula/symex.el#20]
[This PR description](https://github.com/countvajhula/rigpa/pull/4#issue-592653343) discusses the tradeoffs between evil and hydra as modal backends.

Mainly: evil is less intrusive and provides composability, while hydra provides menus and some flexibility with exit points. I think for in-buffer states (like Symex) evil is the more durable option.

### Possible implementation
- `symex` (this package) becomes a package containing only the DSL syntax and semantics, i.e. the language together with its implementation in terms of primitives
- A new package `symex-hydra` that contains the hydra modal interface frontend
- A new package `symex-evil` that contains the evil modal interface frontend
- A new package `symex-runtime` that interfaces with modes for each Lisp flavor to manage the execution environment (e.g. REPL, evaluation, documentation lookups, scratch buffers, etc.).

Related: #9

**Comment by tommy-mor** [comment]
hype. But without hydra for discoverability of keybinds, I think there needs to be a very clear page on what the keybinds do. Eventually something like what parinfer has (https://shaunlebron.github.io/parinfer/), but before that, I think a table like (https://github.com/wbolster/emacs-evil-colemak-basics) would be easy and good

**Comment by countvajhula** [comment]
That's a great point. It shouldn't be too bad to create such a table from [this keybinding list here](https://github.com/countvajhula/symex.el/blob/d37532a9dcff8ec5a2fdc54f27b517890f972bfb/symex-evil.el#L55-L145).

**Comment by countvajhula** [comment]
@tommy-mor added the keybindings, thank you for the suggestion 🙏
