### ISSUE TITLE
Quoted symbols don't work with yank and paste

### ISSUE THREAD

**Issue by markgdawson** [countvajhula/symex.el#23]
Paste doesn't always with quoted symbols. With the symbol in the position shown:

```
((a 'a)
 (b |'b))
```

Using `yp` produces:
```
((a 'a)
 (b 'b 'a)
 (b '))
```

It seems to be picking up the range between this quote mark and the previous one.

With the same initial state, `yP` produces:
```
((a 'a)
 (b ''b))
```
(i.e. double quotes).

**Comment by countvajhula** [comment]
Hi @markgdawson , this should be fixed now. Please let me know if it isn't, and thanks for reporting it :)

**Comment by markgdawson** [comment]
Thanks @countvajhula.
