### ISSUE TITLE
`symex-join-lines-backwords` moves cursor into sexp.

### ISSUE THREAD

**Issue by markgdawson** [countvajhula/symex.el#59]
`symex-join-lines-backwords` doesn't work as I expected when moving a sexp into an empty line above, like this:
```
(+ 1

    |(+ 2))
```
It produces (note the cursor position):
```
(+ 1
     (|+ 2))
```
rather than:
```
(+ 1
     |(+ 2))
```

The inconsistent cursor position means it can't be repeated (either by running the command again or by using the a count).

Removing the call to [foward-char here](https://github.com/countvajhula/symex.el/blob/master/symex-transformations.el#L262) seems to work in every case that I can find.

**Comment by countvajhula** [comment]
Missed seeing this earlier - thanks for reporting it! The code moving forward by a character seems to have had some specific idea behind it, but evidently I neglected to note what it was, and I couldn't detect a failing case after removing it, either 🤷
