### ISSUE TITLE
Error on exiting hydra with activated symbol-highlight

### ISSUE THREAD

**Issue by pepperblue** [countvajhula/symex.el#7]
When I'm trying to exit hydra with `<escape>` while symbol-highlighting is toggled "on" and menu toggled "on", menu disappears but hydra stays active (Message appears "Mark set"). Pressing `<escape>` once more gives the error message `Error in pre-command-hook (hydra--clearfun): (wrong-type-argument keymapp nil)` ...

Procedure that works is:
- Pressing `<escape>`
- Moving to next symbol by pressing `l`
- Pressing `<escape>` again

I'm using Doom-Emacs and did not test this with vanilla Emacs ...

**Comment by countvajhula** [comment]
@pepperblue apologies for the delay -- this should be fixed, let me know if it isn't. Thank you for reporting it 🥇

**Comment by pepperblue** [comment]
@countvajhula this type of work is done in freedom, so - on my side - there are no expectations :sunglasses: 
Thank you for the fix! For me it's working now :+1:
